### PR TITLE
fix: Type hint error

### PR DESCRIPTION
**Pull request by madarve**

### CODE REVIEW

**Comment by madarve** [comment]
Fixes ```TypeError: Parameters to generic types must be types. Got slice(<class 'str'>, typing.Any, None).```

**Comment by Endogen** [comment]
There is already a PR for that: https://github.com/dvf/blockchain/pull/30 It's just that @dvf didn't merge it yet

**Comment by Endogen** [comment]
There is already a PR for that: #19 It's just that @dvf didn't merge it yet

**Comment by madarve** [comment]
Closed due to above comment, lets wait a couple of years :)

**Pull request closed without merging**
