### PR TITLE
Convert unittests to pytest

### PR DESCRIPTION
**Pull request by Mat001**
@dvf Converted unittests into pytests.
Also added route tests which were stale (from dawran6).
All tests are now in pytest.

### CODE REVIEW

**Comment by dvf** [comment]
Hi, do you mind sticking with `unittest` please? I don't see a reason to include another dependency.

**Comment by Mat001** [comment]
@dvf Can I check with you. In https://github.com/dvf/blockchain/pull/12 you were into pytest, now you changed your mind?
Just checking before re-writing all into unittest

**Comment by dvf** [comment]
We ended up going with unittest so as not to add another dependency. Also, pytest’s style of DI is confusing to newcomers. I get that you like pytest, but unless there’s a good reason, I think we should stick with unittest. Don’t you agree?

**Comment by Mat001** [comment]
Yeah, I see. Now that you clarified that the code is aimed more to beginners I agree, unittest would be easier to pick up. And also yes, less dependency, less complexity. I rewrite to unittest.

**Comment by Mat001** [comment]
Added new PR #12 with tests for routes in unittest style.
Closing this PR.

**Pull request closed without merging**
