### PR TITLE
revised docstrings #14

### PR DESCRIPTION
**Pull request by skidzo**
i changed return to returns, too.

### CODE REVIEW

**Comment by dvf** [comment]
@skidzo These docstrings are pretty strange to me. Do you have some references? 

Does anyone else, possibly more experienced than me have any thoughts?

**Comment by skidzo** [comment]
@dvf well, it is the sphinx reference, want to build docs with readthedocs, right?

**Comment by dvf** [comment]
I wasn't really concerned with building docs, since it's such a small project, but possibly in the future. 

Does sphinx recommend you do:

```
...
param my_param: Some parameter
type my_param: int
returns: <bool> Something
```

I was more used to seeing:

```
param my_param: <int> Some parameter
return: <bool> Something
```

Having `type` just seems unnecessary, or don't you agree?

**Comment by skidzo** [comment]
i would wonder if this runs through sphinx with the same output...

have you actually used sphinx before?

**Comment by dvf** [comment]
@skidzo yes, but not with type hinting.

**Comment by skidzo** [comment]
i admit that when autogenerating code this is the best if you want to go for latexpdf output...
I haven't seen the <> notation before, do you have a reference to that?

**Comment by skidzo** [comment]
at least there is an inconsistency for :returns:, there is no :type returns: and actually i would like that....

**Comment by dvf** [comment]
@skidzo do you mind resolving conflicts and updating?

**Pull request closed without merging**
