### PR TITLE
Dvf/tests

### PR DESCRIPTION
**Pull request by seanmmm**
Nov 27 my bitcoin was stolen

### CODE REVIEW

**Comment by Endogen** [comment]
> Nov 27 my bitcoin was stolen
WTF xD

**Comment by seanmmm** [comment]
what is the status of my inquiry? the 27th of november a large amount of my money was sent to a address without my knowledge or permission. i demand a refund and a quick resolution. i did not send it did not know about it and have not heard any explanation as to what happened and why I have been  stolen from.

**Comment by vPlaceCoder** [comment]
> what is the status of my inquiry? the 27th of november a large amount of my money was sent to a address without my knowledge or permission. i demand a refund and a quick resolution. i did not send it did not know about it and have not heard any explanation as to what happened and why I have been stolen from.

Why is this commented here? How is this related to the code here?

@seanmmm 
1. Its january. (23rd) You commented 6 days ago then 4 days ago... so you are talking about something that happened some time ago. 
2. You are asking for a refund. Which is impossible.
3. You should have taken more precautions with you wallet. You got stolen from because you made it easy enough for someone to do it.

**Comment by Endogen** [comment]
Can we please close this fuckup and move on to something that isn't insane???
@seanmmm I really hope you're joking... If you lost bitcoins, it has nothing todo with this project

**Comment by dvf** [comment]
Not really sure what's going on with this. Closing.

**Pull request closed without merging**
