### PR TITLE
Build Docker image using local code

### PR DESCRIPTION
**Pull request by floscha**
Exactly the same as #32 but without the wrong commits so it can be merged now.

### CODE REVIEW

**Comment by yuribol** [comment]
Why do you need virtualenv inside the container? All required packages can be installed in the container itself.

**Comment by floscha** [comment]
That's definitely a valid point. Nevertheless, this is not the point of this pull request (which is only about using the local code instead of pulling it from the repo). So I'm not sure if it makes sense to include it here or rather create a new pull request. I guess this decision should be left to @dvf.

**Comment by dvf** [comment]
@yuribol it's a good point: there's no reason for Virtualenv inside the container. Pipenv is cool but it's a bit expansive for a Docker implementation. Should we go back to just `requirements.txt`?

I'm happy to merge if there are no disagreements.

**Comment by yuribol** [comment]
IMHO, in order to support both ways of development, i.e., with and without docker, I would rollback to having `requirements.txt` file. Side benefit, it will be easier to add support for older version of Python (2.7), as well as be more flexible with the package management tool (although, realistically speaking, pip is de-facto Python's package manager).

With that said, if you want to keep things simple, I'm quite happy with the PR, just wanted to make a suggestion 😃 .

**Comment by floscha** [comment]
I've created a new pull request (#52) now, that adds the requirements.txt and uses it to build the Docker image instead of Pipenv.

So I guess this PR can be merged and closed if @dvf is happy with it.

**Pull request merged**
